import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalDocument, type LegalSection } from '@/components/legal/legal-document';
import { B, Callout, H3, LI, OL, P, UL } from '@/components/legal/legal-primitives';
import { LEGAL } from '@/lib/legal-config';

export const metadata: Metadata = {
  title: 'Terms of Service — SCN Jobs',
  description:
    'The terms that govern your use of SCNJOBS, the job portal operated by SCN Global Pvt Ltd, for job seekers and recruiters.',
};

const link = 'font-medium text-primary hover:underline';
const city = LEGAL.jurisdictionCity;

const sections: LegalSection[] = [
  {
    id: 'acceptance',
    title: 'Acceptance of these Terms',
    body: (
      <>
        <P>
          These Terms of Service (“<B>Terms</B>”) are a legally binding agreement between you and <B>{LEGAL.company}</B>{' '}
          (“<B>{LEGAL.brand}</B>”, “we”, “us”) governing your access to and use of {LEGAL.domain} and all related
          websites, dashboards, notifications and services (the “<B>Platform</B>”).
        </P>
        <P>
          By creating an account, ticking the agreement checkbox, or otherwise accessing or using the Platform, you
          agree to these Terms, our <Link href="/privacy" className={link}>Privacy Policy</Link>, which is incorporated by reference. If you use
          the Platform on behalf of a company, you confirm you have authority to bind that company. If you do not agree,
          do not use the Platform.
        </P>
        <P>
          These Terms are an electronic record under the Information Technology Act, 2000 and the rules under it. They
          are generated by a computer system and do not require a physical or digital signature.
        </P>
      </>
    ),
  },
  {
    id: 'definitions',
    title: 'Definitions',
    body: (
      <UL>
        <LI><B>Worker</B> or <B>Job Seeker</B>: an individual who registers to search and apply for jobs.</LI>
        <LI><B>Recruiter</B>: an individual or organisation that uses the Platform to post jobs or find candidates.</LI>
        <LI><B>User</B>: any Worker, Recruiter or other person using the Platform.</LI>
        <LI><B>User Content</B>: any information, profile, resume, photo, job posting, message or other material that a User submits to the Platform.</LI>
        <LI><B>Applicable Law</B>: all Indian laws, rules and regulations that apply to a matter, including labour and employment, anti-discrimination, data-protection and information-technology laws.</LI>
      </UL>
    ),
  },
  {
    id: 'service',
    title: 'What SCNJOBS is (and is not)',
    body: (
      <>
        <P>
          SCNJOBS is an online platform that helps Workers and Recruiters find each other. We act as an{' '}
          <B>intermediary</B> within the meaning of the Information Technology Act, 2000.
        </P>
        <Callout tone="warning" title="Important">
          <UL>
            <LI>We are <B>not</B> an employer, staffing contractor or party to any employment arrangement between a Worker and a Recruiter.</LI>
            <LI>We do not guarantee that you will get a job, an interview, a candidate, a particular salary or any specific result.</LI>
            <LI>Although we make reasonable efforts to review Recruiters and postings, we cannot verify every statement. Do your own due diligence before accepting an offer, sharing documents or paying anyone.</LI>
            <LI>Terms of employment (pay, hours, benefits, location, notice) are between the Worker and the Recruiter alone.</LI>
          </UL>
        </Callout>
      </>
    ),
  },
  {
    id: 'eligibility',
    title: 'Eligibility and accounts',
    body: (
      <>
        <OL>
          <LI>You must be at least <B>18 years old</B> and legally capable of entering into a binding contract under the Indian Contract Act, 1872.</LI>
          <LI>You must provide accurate, current and complete information and keep it updated. You must verify your phone number and/or email using the OTP we send.</LI>
          <LI>One person may hold one Worker account. You must not create accounts using another person’s identity or contact details.</LI>
          <LI>Some Recruiter accounts may be created or approved by us after verification. We may ask for business documents and may refuse or revoke access at our discretion, acting reasonably.</LI>
          <LI>You are responsible for keeping your password and OTPs confidential and for all activity under your account. Tell us immediately at {LEGAL.emails.support} if you suspect unauthorised use.</LI>
        </OL>
      </>
    ),
  },
  {
    id: 'workers',
    title: 'Terms for Workers',
    body: (
      <>
        <UL>
          <LI>Your profile and resume must be truthful. Do not claim qualifications, experience or identity you do not have.</LI>
          <LI>By applying for a job, you authorise us to share your application and profile details with the Recruiter that posted it, and you understand Verified Recruiters may search and view your profile, as described in the <Link href="/privacy#sharing" className={link}>Privacy Policy</Link>.</LI>
          <LI>You should <B>never pay money</B> to anyone to obtain a job, an interview or a “registration” through the Platform. Recruiters are prohibited from charging candidates. If anyone asks you for money, stop and report it to us immediately.</LI>
          <LI>Do not share your OTP, password or sensitive identity or bank details with anyone claiming to represent us or a Recruiter.</LI>
          <LI>Apply only for jobs you genuinely intend to pursue and respond to Recruiters professionally.</LI>
        </UL>
      </>
    ),
  },
  {
    id: 'recruiters',
    title: 'Terms for Recruiters',
    body: (
      <>
        <P>If you post jobs or access candidate data, you additionally agree that you will:</P>
        <UL>
          <LI>Post only <B>genuine, current</B> openings that you are authorised to fill, with accurate title, location, pay range, working conditions and requirements. Remove or close postings once filled.</LI>
          <LI><B>Never charge</B> any fee, deposit, “registration”, training or security amount from candidates, directly or indirectly, for a job or interview.</LI>
          <LI>Comply with Applicable Law, including labour, wage, anti-discrimination and equal-opportunity requirements. Any gender, age or similar preference in a posting must be a genuine occupational requirement permitted by law; we may edit or remove postings that appear discriminatory.</LI>
          <LI>Use candidate data <B>only</B> to evaluate and contact candidates for the opening they applied to, or for genuine recruitment for your organisation. You must not sell, rent, publish, scrape, bulk-export for unrelated purposes, or share candidate data with third parties, or use it for marketing.</LI>
          <LI>Protect candidate data with reasonable security safeguards, delete it when it is no longer needed, honour candidate requests for correction or deletion, and tell us promptly if you learn of any breach.</LI>
          <LI>Keep your account credentials confidential and limit access to authorised personnel. You are responsible for their acts.</LI>
          <LI>Provide accurate company information and, when asked, documents that prove your business identity.</LI>
          <LI>Treat candidates respectfully and update application statuses honestly and promptly.</LI>
        </UL>
        <P>
          You are an independent data fiduciary for any candidate data you take from the Platform and are responsible
          for your own compliance with the DPDP Act.
        </P>
      </>
    ),
  },
  {
    id: 'conduct',
    title: 'Acceptable use',
    body: (
      <>
        <P>You must not, and must not help anyone to:</P>
        <UL>
          <LI>Submit false, misleading, fraudulent or impersonating information, or pretend to be another person or organisation.</LI>
          <LI>Post content that is unlawful, defamatory, obscene, pornographic, hateful, harassing, discriminatory, threatening, invasive of another’s privacy, or that promotes violence, or that infringes any intellectual property or other right.</LI>
          <LI>Post jobs or messages that are scams, pyramid or multi-level schemes, advertise illegal work, or ask for money, deposits or sensitive personal or financial information from candidates.</LI>
          <LI>Collect, scrape, crawl or harvest data from the Platform using bots or automated means, or use the Platform to build a competing database.</LI>
          <LI>Send spam, unsolicited commercial messages or chain messages.</LI>
          <LI>Upload viruses or malicious code, probe or test the security of the Platform, bypass authentication or rate limits, or interfere with its operation.</LI>
          <LI>Access accounts, data or admin areas you are not authorised to access.</LI>
          <LI>Reverse engineer, decompile, copy, modify or create derivative works of the Platform, except as permitted by law.</LI>
          <LI>Use the Platform in violation of Applicable Law or to harm a minor in any way.</LI>
        </UL>
      </>
    ),
  },
  {
    id: 'content',
    title: 'Your content and licence',
    body: (
      <>
        <P>
          You keep ownership of your User Content. You grant {LEGAL.company} a non-exclusive, royalty-free, worldwide,
          sub-licensable (to our service providers only) licence to host, store, reproduce, display, transmit and
          process your User Content solely to operate, secure, provide and improve the Platform, and to show it to other
          Users as described in these Terms and the Privacy Policy. This licence ends when you delete the content or
          your account, except for copies in backups, copies already shared with Recruiters, and where we must retain
          them by law.
        </P>
        <P>
          You confirm that you own or have the right to submit your User Content and that it does not violate these
          Terms or anyone’s rights.
        </P>
        <P>
          We may remove or disable access to any content that we reasonably believe violates these Terms or the law, and
          we may act on takedown requests and government orders as required under the Information Technology
          (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.
        </P>
      </>
    ),
  },
  {
    id: 'ip',
    title: 'Our intellectual property',
    body: (
      <P>
        The Platform, including its software, design, text, graphics, logos, the “SCNJOBS” name and all related
        intellectual property, belongs to {LEGAL.company} or its licensors. We grant you a limited, non-exclusive,
        non-transferable, revocable right to use the Platform for its intended purpose in accordance with these Terms. No
        other rights are granted. Feedback you give us may be used by us without obligation to you.
      </P>
    ),
  },
  {
    id: 'fees',
    title: 'Fees and payments',
    body: (
      <P>
        Core features for Workers are offered at no charge unless we clearly state otherwise. If we introduce paid
        features or plans (for example for Recruiters), the price, taxes (including GST), billing period and refund
        terms will be shown before you pay, and you will pay only after you accept them. We may change prices prospectively
        with reasonable notice. Except where the law or our stated refund terms say otherwise, fees once paid are
        non-refundable.
      </P>
    ),
  },
  {
    id: 'third-parties',
    title: 'Third-party services and links',
    body: (
      <P>
        The Platform may rely on or link to third-party services (such as messaging, file storage or a Recruiter’s
        website). We are not responsible for third-party content, services or practices, and your use of them is at your
        own risk and subject to their terms.
      </P>
    ),
  },
  {
    id: 'suspension',
    title: 'Suspension and termination',
    body: (
      <>
        <P>
          You may stop using the Platform and delete your account at any time from your dashboard or by contacting us.
        </P>
        <P>
          We may suspend, restrict or terminate your access, remove content or postings, or withhold services, with or
          without notice, if we reasonably believe you have breached these Terms or the law, created risk or legal
          exposure for us or other Users, provided false information, or if required by law or a competent authority. Where
          practicable and lawful, we will tell you why and give you a chance to respond.
        </P>
        <P>
          Sections that by their nature should survive termination (including content licence for retained copies,
          intellectual property, disclaimers, limitation of liability, indemnity and governing law) will survive.
        </P>
      </>
    ),
  },
  {
    id: 'disclaimer',
    title: 'Disclaimers',
    body: (
      <>
        <P>
          To the fullest extent permitted by law, the Platform is provided on an “<B>as is</B>” and “<B>as available</B>”
          basis. We do not warrant that the Platform will be uninterrupted, error-free or secure; that job listings,
          candidate profiles or other User Content are accurate, complete or lawful; or that any use of the Platform
          will lead to employment, a hire or any particular outcome.
        </P>
        <P>
          We are not responsible for the acts or omissions of any User, including any dispute between a Worker and a
          Recruiter about hiring, wages, conduct or termination.
        </P>
      </>
    ),
  },
  {
    id: 'liability',
    title: 'Limitation of liability',
    body: (
      <>
        <P>
          To the maximum extent permitted by Applicable Law, {LEGAL.company}, its directors, employees and affiliates
          will not be liable for any indirect, incidental, special, consequential or punitive damages, or for loss of
          profits, income, opportunity, goodwill or data, arising out of or in connection with your use of (or inability
          to use) the Platform or any dealings with other Users.
        </P>
        <P>
          Our total aggregate liability for all claims relating to the Platform will not exceed the greater of (a) the
          amount you paid us in the 12 months before the event giving rise to the claim, and (b) ₹1,000.
        </P>
        <P>
          Nothing in these Terms excludes or limits liability that cannot be excluded or limited under Applicable Law,
          including liability for fraud or wilful misconduct, or any rights you have as a consumer under law.
        </P>
      </>
    ),
  },
  {
    id: 'indemnity',
    title: 'Indemnity',
    body: (
      <P>
        You agree to indemnify and hold harmless {LEGAL.company} and its directors, officers, employees and affiliates from
        any claim, loss, liability, damages and reasonable legal costs arising out of your User Content, your breach of
        these Terms or Applicable Law, or your infringement of another person’s rights. We will give you reasonable
        notice of any claim and you agree to cooperate in its defence.
      </P>
    ),
  },
  {
    id: 'reporting',
    title: 'Reporting abuse and grievances',
    body: (
      <>
        <P>
          To report a suspicious job posting, a Recruiter who asks for money, a misuse of your data, offensive content or
          any other concern, contact us at{' '}
          <a href={`mailto:${LEGAL.emails.support}`} className={link}>{LEGAL.emails.support}</a> or our Grievance Officer
          as set out in the{' '}
          <Link href="/privacy#grievance" className={link}>Privacy Policy</Link>. We acknowledge complaints within 24
          hours and aim to resolve them within 15 days.
        </P>
        <P>
          Please include the job or profile link, screenshots and any relevant details so we can act quickly.
        </P>
      </>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to the Platform and Terms',
    body: (
      <>
        <P>
          We may modify, suspend or discontinue any part of the Platform at any time. We may also update these Terms. The
          version and date at the top show the latest revision. For material changes we will give reasonable notice
          through the Platform, email or SMS. By continuing to use the Platform after the change takes effect you accept
          the revised Terms. If you do not agree, you must stop using the Platform and may delete your account.
        </P>
      </>
    ),
  },
  {
    id: 'law',
    title: 'Governing law and disputes',
    body: (
      <>
        <P>
          These Terms are governed by the laws of India, without regard to conflict-of-law principles.
        </P>
        <OL>
          <LI><B>Talk first.</B> If a dispute arises, contact us as described above and we will try in good faith to resolve it within 30 days.</LI>
          <LI>
            <B>Arbitration.</B> If it is not resolved, the dispute will be finally settled by arbitration under the
            Arbitration and Conciliation Act, 1996 before a sole arbitrator appointed by mutual agreement (or, failing
            agreement, as provided by that Act). {city ? `The seat and venue of arbitration will be ${city}, India. ` : ''}
            The language will be English.
          </LI>
          <LI>
            <B>Courts.</B> Subject to the above, the courts {city ? `at ${city}, India` : 'of competent jurisdiction in India'}{' '}
            will have exclusive jurisdiction over any matter that may be brought before a court, including interim
            relief.
          </LI>
        </OL>
        <P>
          Nothing here limits any non-waivable right you have as a consumer to approach a consumer commission or other
          forum under Applicable Law.
        </P>
      </>
    ),
  },
  {
    id: 'general',
    title: 'General',
    body: (
      <UL>
        <LI><B>Entire agreement.</B> These Terms and the Privacy Policy form the entire agreement between you and us about the Platform.</LI>
        <LI><B>Severability.</B> If any provision is held unenforceable, the rest remains in effect and the provision will be enforced to the extent permitted.</LI>
        <LI><B>No waiver.</B> Our failure to enforce a right is not a waiver of it.</LI>
        <LI><B>Assignment.</B> You may not assign these Terms without our written consent. We may assign them to an affiliate or a successor to our business.</LI>
        <LI><B>Force majeure.</B> We are not liable for delay or failure caused by events beyond our reasonable control.</LI>
        <LI><B>Relationship.</B> Nothing here creates a partnership, agency, franchise or employment relationship between you and us.</LI>
        <LI><B>Notices.</B> We may give notice by posting on the Platform or by email, SMS or in-app message to your registered details. You may contact us at {LEGAL.emails.legal}.</LI>
      </UL>
    ),
  },
  {
    id: 'contact',
    title: 'Contact us',
    body: (
      <div className="rounded-xl border border-border bg-card p-5 text-[15px] leading-7 text-muted-foreground">
        <p className="font-semibold text-foreground">{LEGAL.company}</p>
        {LEGAL.registeredAddress && <p>{LEGAL.registeredAddress}</p>}
        <p>
          Email: <a href={`mailto:${LEGAL.emails.legal}`} className={link}>{LEGAL.emails.legal}</a>
        </p>
        <p>Phone: {LEGAL.phone}</p>
        <p>Hours: {LEGAL.supportHours}</p>
      </div>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <LegalDocument
      current="terms"
      title="Terms of Service"
      summary="The rules for using SCNJOBS as a job seeker or a recruiter. Please read them carefully."
      sections={sections}
    />
  );
}